.TH "src/input.cpp" 3 "Fri May 17 2019" "Cellular Automaton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/input.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/input\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshow_help\fP ()"
.br
.RI "Show the arguments available from cli\&. "
.ti -1c
.RI "int \fBreadOptions\fP (int argc, char *argv[], \fBLife\fP &life)"
.br
.RI "Read the arguments from cli\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jefferson Bruno, Ranieri Santos 
.RE
.PP
\fBDate:\fP
.RS 4
22/05/2019 
.RE
.PP

.PP
Definition in file \fBinput\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int readOptions (int argc, char * argv[], \fBLife\fP & life)"

.PP
Read the arguments from cli\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Number of arguments\&. 
.br
\fIargv\fP Array of arguments\&. 
.br
\fI&life\fP Object used to save options 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::invalid_argument\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if success, and -1 if failed\&. 
.RE
.PP

.PP
Definition at line 29 of file input\&.cpp\&.
.SS "void show_help ()"

.PP
Show the arguments available from cli\&. 
.PP
Definition at line 10 of file input\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cellular Automaton from the source code\&.
