.TH "include/life.h" 3 "Fri May 17 2019" "Cellular Automaton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/life.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.RI "Status of the cell\&. "
.ti -1c
.RI "class \fBLife\fP"
.br
.ti -1c
.RI "struct \fBLife::Options\fP"
.br
.RI "Save command line arguments\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBempty\fP = \-1"
.br
.RI "No cell\&. "
.ti -1c
.RI "const int \fBdead\fP = 0"
.br
.RI "Dead cell\&. "
.ti -1c
.RI "const int \fBalive\fP = 1"
.br
.RI "Alive cell\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int alive = 1"

.PP
Alive cell\&. 
.PP
Definition at line 12 of file life\&.h\&.
.SS "const int dead = 0"

.PP
Dead cell\&. 
.PP
Definition at line 11 of file life\&.h\&.
.SS "const int empty = \-1"

.PP
No cell\&. 
.PP
Definition at line 10 of file life\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cellular Automaton from the source code\&.
