.TH "Life" 3 "Fri May 17 2019" "Cellular Automaton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Life
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <life\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOptions\fP"
.br
.RI "Save command line arguments\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLife\fP (data_type M, data_type N)"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fB~Life\fP ()"
.br
.RI "Desconstructor\&. "
.ti -1c
.RI "void \fBprint_options\fP ()"
.br
.RI "Print the command line arguments\&. "
.ti -1c
.RI "void \fBprint\fP ()"
.br
.RI "Print the board\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBLife::Options\fP \fBoptions\fP"
.br
.RI "Initialize the struct\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file life\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Life::Life (data_type M, data_type N)\fC [inline]\fP"

.PP
Default constructor\&. 
.PP
Definition at line 32 of file life\&.h\&.
.SS "Life::~Life ()\fC [inline]\fP"

.PP
Desconstructor\&. 
.PP
Definition at line 43 of file life\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Life::print ()\fC [inline]\fP"

.PP
Print the board\&. 
.PP
Definition at line 73 of file life\&.h\&.
.SS "void Life::print_options ()\fC [inline]\fP"

.PP
Print the command line arguments\&. 
.PP
Definition at line 60 of file life\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBLife::Options\fP  Life::options"

.PP
Initialize the struct\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cellular Automaton from the source code\&.
