.TH "Life::Options" 3 "Fri May 17 2019" "Cellular Automaton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Life::Options \- Save command line arguments\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <life\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmaxgen\fP = 100"
.br
.RI "Maximum number of generations\&. "
.ti -1c
.RI "int \fBfps\fP = 2"
.br
.RI "Number of generations presented per second\&. "
.ti -1c
.RI "int \fBblocksize\fP = 5"
.br
.RI "Pixel size of a cell\&. "
.ti -1c
.RI "std::string \fBalivecolor\fP = 'RED'"
.br
.RI "Color name for representing alive cells\&. "
.ti -1c
.RI "std::string \fBbkgcolor\fP = 'GREEN'"
.br
.RI "Color name for the background\&. "
.ti -1c
.RI "std::string \fBimgdir\fP = 'data/images/'"
.br
.RI "Directory where output images are written to\&. "
.ti -1c
.RI "std::string \fBinputfile\fP"
.br
.RI "Filename for the input file\&. "
.ti -1c
.RI "std::string \fBoutfile\fP = 'data/log\&.txt'"
.br
.RI "Filename for the output file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Save command line arguments\&. 
.PP
Definition at line 47 of file life\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string Life::Options::alivecolor = 'RED'"

.PP
Color name for representing alive cells\&. 
.PP
Definition at line 51 of file life\&.h\&.
.SS "std::string Life::Options::bkgcolor = 'GREEN'"

.PP
Color name for the background\&. 
.PP
Definition at line 52 of file life\&.h\&.
.SS "int Life::Options::blocksize = 5"

.PP
Pixel size of a cell\&. 
.PP
Definition at line 50 of file life\&.h\&.
.SS "int Life::Options::fps = 2"

.PP
Number of generations presented per second\&. 
.PP
Definition at line 49 of file life\&.h\&.
.SS "std::string Life::Options::imgdir = 'data/images/'"

.PP
Directory where output images are written to\&. 
.PP
Definition at line 53 of file life\&.h\&.
.SS "std::string Life::Options::inputfile"

.PP
Filename for the input file\&. 
.PP
Definition at line 54 of file life\&.h\&.
.SS "int Life::Options::maxgen = 100"

.PP
Maximum number of generations\&. 
.PP
Definition at line 48 of file life\&.h\&.
.SS "std::string Life::Options::outfile = 'data/log\&.txt'"

.PP
Filename for the output file\&. 
.PP
Definition at line 55 of file life\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cellular Automaton from the source code\&.
