.TH "include/simulation.h" 3 "Fri May 24 2019" "Version 0.1" "Cellular Automaton" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/simulation.h
.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulation\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSim_H\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBalive\fP = 1"
.br
.RI "Auxiliar constants\&. "
.ti -1c
.RI "const int \fBdead\fP = 0"
.br
.RI "Dead cell\&. "
.ti -1c
.RI "const int \fBint_size\fP = 2147483647"
.br
.RI "Standard value to maximum number of generations, 'Infinite'\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Sim_H"

.PP
Definition at line 2 of file simulation\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const int alive = 1"

.PP
Auxiliar constants\&. Alive cell\&. 
.PP
Definition at line 20 of file simulation\&.h\&.
.SS "const int dead = 0"

.PP
Dead cell\&. 
.PP
Definition at line 21 of file simulation\&.h\&.
.SS "const int int_size = 2147483647"

.PP
Standard value to maximum number of generations, 'Infinite'\&. 
.PP
Definition at line 22 of file simulation\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Cellular Automaton from the source code\&.
